### ISSUE TITLE
cant find attachments in query even with filled ATTACHMENTS_DIR

### ISSUE THREAD

**Issue by specter119** [deanishe/zothero#19]
I have set "Linked Attachment Base Directory" in Zotero, and all my attachments can be launched in Zotero directly.
but in ZotHero, only the items with "URL link" and "File" are displayed as owning attachments, what we want is defiantly "File link", but none of the file link attachments is shown on my query.
I have tried to set the ATTACHMENTS_DIR,  it makes any difference.
My file links are generated by [ZotFile](https://github.com/jlegewie/zotfile), and my attachments are mainly stored in the subdirectory (or even more "sub") of the "Linked Attachment Base Directory" in Zotero(because I define the subdirectory name as collection path in Zotero with ZotFile)

Thanks for your workflow, I hope my message will help, maybe the issue is related to the paths of file links related to the subfolder?

**Comment by deanishe** [comment]
> I have set "Linked Attachment Base Directory" in Zotero

Then ATTACHMENTS_DIR must be set to the same path or the workflow cannot find the attached files.

I can't tell you what the problem might be, I'm afraid, because I can't replicate your problem from this information.

Please check the log file (enter `zotconf` in Alfred and choose Open Log File), and search for "attachment". There should be a warning message for each attachment the workflow can't locate telling you what the problem is.

**Comment by specter119** [comment]
like

> 10:50:57 zotero.py:324 WARNING  [zotero] can't access attachment "Functional Materials/Thermoelectric/Concept/Structure/Organic/Huang et al_2016_Bismuth Interfacial Doping of Organic Small Molecules for High Performance.pdf": attachments directory is unset

related logs all end with "attachments directory is unset", no matter I leave  ATTACHMENTS_DIR blank or set it as the abs path of "Linked Attachment Base Directory"

---

but it is fixed after I filled the ATTACHMENTS_DIR and Reload Zotero Data, Thanks.
I think it will be nice if you mentioned this extra reload if the user doesn't set the right ATTACHMENTS_DIR before the first query.
