### ISSUE TITLE
Would you mind reading the ZOTERO_DIR and ATTACHMENTS_DIR directly from system?

### ISSUE THREAD

**Issue by specter119** [deanishe/zothero#21]
I once wrote a python script related to `ZOTERO_DIR` and `ATTACHMENTS_DIR`, I think add it to ZotHero will not be too complicated.

You can see it here <https://gist.github.com/specter119/b79dc35a6091d0fd0896a9536fbddb5a>, but it will need `configparser`,  I am not sure it's a build in package or not.

thanks, if you need, I will send a PR when I'm free.

**Comment by deanishe** [comment]
That's a very good idea. I'll look into it.

> I think add it to ZotHero will not be too complicated

Maybe, maybe not. Your script assumes `Profile0`, but is that always correct? Does Zotero actually use profiles, or do they just exist because it's based on Firefox?

> I am not sure it's a build in package or not

Yes, `ConfigParser` is a built-in library (but called `ConfigParser`, not `configparser` in Python 2).

**Comment by deanishe** [comment]
I've updated ZotHero to read Zotero's config files. We'll see if it works well, I guess…
